#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

arg1=$1

styles_root="./styles/books"

# Pull in the style names. No dependency on books.txt needed,
# using the directory structure instead.
PLATFORMS=(pdf)
STYLE_NAMES=()
for style in $(ls $styles_root); do STYLE_NAMES+=("${style}"); done

if [ ! "${arg1}" == "" ]; then
  STYLE_NAMES=("${arg1}")
fi

output_dir="./styles/output"

if [[ ${#STYLE_NAMES[@]} == 0 ]]; then
  die "No styles were found. Check $styles_root"
fi

for i in "${!STYLE_NAMES[@]}"; do
  style_name="${STYLE_NAMES[i]}"
  if [[ $style_name == "generic" ]]; then continue; fi # skip generic
  sass_file="${styles_root}/${style_name}/book.scss"
  for platform in "${PLATFORMS[@]}"; do
    css_file="${output_dir}/${style_name}-${platform}.css"

    PLATFORM="${platform}" do_progress "Generating ${css_file} $((i + 1))/${#STYLE_NAMES[@]}" \
      node styles/build/build.js "${sass_file}" "${css_file}"
  done

  #disable web styles for the time being
  #do_progress "Building webpackable _web-styles.json" \
  #  npm run-script build:web-styles
  
done
