#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

arg1=$1

styles_root="./styles/books"

# Pull in the BOOK_CONFIGS and STYLE_NAMES
source ./books.txt || exit 1

if [ ! "${arg1}" == "" ]; then
  STYLE_NAMES=("${arg1} ${arg1}")
fi

output_dir="./styles/output"

if [[ ${#STYLE_NAMES[@]} == 0 ]]; then
  die "No styles were found. Check books.txt"
fi

for style_config in "${STYLE_NAMES[@]}"; do
  read -r style_name _ <<< "${style_config}"

  sass_file="${styles_root}/${style_name}/book.scss"

  for platform in "${PLATFORMS[@]}"; do
    css_file="${output_dir}/${style_name}-${platform}.css"

    PLATFORM="${platform}" do_progress "Generating ${css_file}" \
      node styles/build/build.js "${sass_file}" "${css_file}"
  done

  do_progress "Building webpackable _web-styles.json" \
    npm run-script build:web-styles
  
done
