#!/bin/bash

usage="script/build-impacted-styles <theme> <shape_name (optional)>"
if [[ $# -lt 1 ]] ; then
    echo "Not enough args"
    echo $usage
    exit 1
fi

cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

theme=$1
shape_name=$2

styles_root="./styles/books"
output_dir="./styles/output"

search_string="$theme:::$shape_name"
book_files=($(grep -R -l $search_string $styles_root))
echo "Found ${#book_files[@]} files with instances of $search_string."
echo `grep -R -l $search_string $styles_root`

PLATFORMS=(pdf)
for i in "${!book_files[@]}"; do
    sass_file=${book_files[i]}
    style_name=$(cut -d / -f 4 <<< $sass_file)

    css_file="${output_dir}/${style_name}-pdf.css"

    do_progress "Generating ${css_file} $((i + 1))/${#book_files[@]}" \
      dart styles/build/build.dart "${sass_file}" "${css_file}"
done
