#!/usr/bin/env bash

set -Eeuo pipefail

destination="`pwd`/styles/output/downloaded-fonts"

run() {
    destination_css="${destination}/$1.css"
    if [[ -f "$destination_css" ]]
    then
        echo "Skipping $1 because file already exists"
    else
        ./script/download-single-font --destination "$destination" --name "$1" "$2"
    fi
}


[[ ! -d "$destination" ]] && mkdir -p "$destination"

run "Archivo"             'https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700&display=swap&subset=latin,latin-ext'
run "Archivo-Black"       'https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap&subset=latin,latin-ext'
run "Courier-Prime"       'https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap'
run "Dosis"               'https://fonts.googleapis.com/css2?family=Dosis:wght@400;700&display=swap&subset=latin,latin-ext'
run "IBM-Plex-Mono"       'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono'
run "IBM-Plex-Sans"       'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@200;300;400;500;700&display=swap&subset=latin,latin-ext'
run "IBM-Plex-Serif"      'https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:wght@400;700&display=swap&subset=latin,latin-ext'
run "Mulish"              'https://fonts.googleapis.com/css2?family=Mulish:wght@400;500;600;700;900&display=swap&subset=latin,latin-ext'
run "Noto-Sans"           'https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap&subset=latin,latin-ext'
run "Roboto-Condensed"    'https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&display=swap&subset=latin,latin-ext'
run "Roboto-Slab"         'https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;700&display=swap&subset=latin,latin-ext'

