#!/bin/bash

set -e

env_vars=()

while echo "$1" | grep -q '='
do
  env_vars[${#env_vars[@]}]='-e'
  env_vars[${#env_vars[@]}]="$1"
  shift
done

docker build -f Dockerfile -t styles-base .
docker build -f Dockerfile.run -t styles-full .
docker run -d -t --rm --mount type=bind,source="$PWD",target=/code --name styles_temp_container styles-full /bin/bash
echo "Executing $@..."
docker exec "${env_vars[@]}" styles_temp_container "$@"
docker stop styles_temp_container > /dev/null    # mutes "styles_temp_container" output
