# Debug workflows with act: https://nektosact.com/installation/homebrew.html

name: Check for compiled styles

on:
  pull_request:

jobs:
  matches:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: yarn install
      - name: Compile styles
        run: node ./styles/build/build.js
      - name: Check that compiled styles match output folder
        run: |
          git diff
          git diff-index --quiet HEAD
