---
name: tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
      - uses: c-hive/gha-yarn-cache@v2
      - name : Install npm dependencies
        run: SKIP_MY_POSTINSTALL=true yarn install
      - name: Build Recipes
        run: ./script/build-recipes
      - name: Build styles
        run: ./script/build-styles
      - name: Verify recipes and styles were committed
        run: |
          git diff
          git diff-index --quiet HEAD
